![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises

In [1]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

2.2.2

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [2]:
a = pd.Series()

In [ ]:
pd.Series()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [5]:
X = ['A','B','C']
print(X, type(X))
Y = pd.Series(X)
print(Y, type(Y))
Y

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

0    A
1    B
2    C
dtype: object

In [ ]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [9]:
X = pd.Series(['A','B','C'])
X.name = 'My letters'
X

0    A
1    B
2    C
Name: My letters, dtype: object

In [10]:
X = pd.Series(['A','B','C'])

X.name = 'My letters'
X

0    A
1    B
2    C
Name: My letters, dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values

In [14]:
X = pd.Series(['A','B','C'])
X.values

array(['A', 'B', 'C'], dtype=object)

In [15]:
X = pd.Series(['A','B','C'])

X.values

array(['A', 'B', 'C'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series

In [17]:
X = pd.Series(['A','B','C'])
X.index = ["Almaty","Barys","Canada"]
X

Almaty    A
Barys     B
Canada    C
dtype: object

In [ ]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element

In [20]:
X = pd.Series((['A','B','C']), index = ['first', 'second', 'third'])
X.iloc(0)
X['first']

'A'

In [21]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element

In [23]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])
X[-1]
X.iloc[-1]
X['third']
X

/tmp/ipykernel_18438/3758905910.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[-1]

first     A
second    B
third     C
dtype: object

In [ ]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[-1] # by position
#X.iloc[-1] # by position
X['third'] # by index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements

In [24]:
X = pd.Series(['A','B','C','D','E'], index=['first', 'second', 'third', 'fourth', 'fives'])
X[1:-1]

second    B
third     C
fourth    D
dtype: object

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['second', 'third', 'forth']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position

In [27]:
X = pd.Series(['A','B','C','D','E'], index=['first', 'second', 'third', 'fourth', 'fives'])
X[::-1]

fives     E
fourth    D
third     C
second    B
first     A
dtype: object

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements

In [31]:
X = pd.Series(['A','B','C','D','E'], index=['first','second','third','forth','fifth'])
X[['first','fifth']]

first    A
fifth    E
dtype: object

In [32]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

/tmp/ipykernel_18438/1500303121.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[[0, -1]]

first    A
fifth    E
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float

In [33]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
pd.Series(X, dtype = np.float64)

first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float64

In [34]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [35]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
X = X[::-1]

In [36]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

fifth     5
forth     4
third     3
second    2
first     1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series

In [41]:
X = np.sort(pd.Series([4,2,3,7,8],
              index=['first','second','third','forth','fifth']))
X

array([2, 3, 4, 7, 8])

In [42]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10

In [46]:
X = pd.Series([4,2,5,1,3],index=['forth','second','fifth','first','third'])
X[4] = 10
X

/tmp/ipykernel_18438/2747364382.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  X[4] = 10

forth      4
second     2
fifth      5
first      1
third     10
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[4] = 10
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0

In [48]:
X = pd.Series([1,2,3,4,5], index = ['A','B','C','D','E'])
X[1:-1] = 0
X

A    1
B    0
C    0
D    0
E    5
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element

In [49]:
X = pd.Series([1,2,3,4,5], index = ['A','B','C','D','E'])
X = X + 5
X

A     6
B     7
C     8
D     9
E    10
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements

In [50]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements

In [51]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

In [52]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5

In [54]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >= 0
X[mask]

1     2
2     0
4     5
5     6
6     0
7     0
9    10
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [56]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X > X.mean()
X[mask]

1     2
4     5
5     6
9    10
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10

In [58]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

1     2
9    10
dtype: int64

In [59]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

1     2
9    10
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

[Текст ссылки](https://)### Given the X pandas Series, return True if none of its elements is zero

In [68]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X != 0
mask.all()

np.False_

In [62]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

np.False_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero

In [69]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
X.any()

np.True_

In [70]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

np.True_

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements

In [71]:
X = pd.Series([3,5,6,7,2,3,4,5,5])
X[1:4].sum()

np.int64(18)

In [ ]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [73]:
X = pd.Series([3,5,6,7,2,3,4,5,5])
X.mean()

np.float64(4.444444444444445)

In [74]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

np.float64(3.7)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [75]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])
X.max()

10

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)